services:
  haproxy:
    image: haproxy:2.9-dev7-alpine
    container_name: haproxy
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8080:80"
      - "8088:88"
    depends_on:
      - nginx1
      - nginx2

  nginx1:
    image: nginx
    container_name: nginx1
    volumes:
      - ./config/loadbalancer.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80"
    depends_on:
      - node1
      - node2
      - node3

  nginx2:
    image: nginx
    container_name: nginx2
    volumes:
      - ./config/loadbalancer.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80"
    depends_on:
      - node1
      - node2
      - node3

  node1:
    image: nginx
    container_name: node1
    volumes:
      - ./config/node.conf:/etc/nginx/conf.d/default.conf
      - ./html/node1.html:/usr/share/nginx/html/index.html
    ports:
      - "80"

  node2:
    image: nginx
    container_name: node2
    volumes:
      - ./config/node.conf:/etc/nginx/conf.d/default.conf
      - ./html/node2.html:/usr/share/nginx/html/index.html
    ports:
      - "80"

  node3:
    image: nginx
    container_name: node3
    volumes:
      - ./config/node.conf:/etc/nginx/conf.d/default.conf
      - ./html/node3.html:/usr/share/nginx/html/index.html
    ports:
      - "80"
